added-sector-service
udisinghania/socgen-stockmarket-project pull request #3
Opened 2021-07-16 09:46 UTC by udisinghania

2021-07-16 10:02 UTC, ujjwal0507 commented on backend/sector-service/src/main/java/com/example/sectorservice/controllers/SectorController.java
> +
Controller routes shoudl return Response Entity

2021-07-16 10:04 UTC, ujjwal0507 commented on backend/sector-service/src/test/java/com/example/sectorservice/SectorServiceApplicationTests.java
> +
Delete the empty class.

2021-07-16 10:06 UTC, ujjwal0507 commented on backend/sector-service/pom.xml
> +		<groupId>org.springframework.boot</groupId>
Chagne the parent so that it refers to the parent pom file.

2021-07-16 10:06 UTC, ujjwal0507 commented on backend/sector-service/pom.xml
> +		<dependency>
Dependency alredy present in the parent pom.

2021-07-16 10:07 UTC, ujjwal0507 commented on backend/sector-service/pom.xml
> +		<dependency>
Dependency already present in the parent pom

2021-07-16 10:07 UTC, ujjwal0507 commented on backend/sector-service/pom.xml
> +	<build>
Build plugins are present in the parent pom file.

2021-07-16 10:08 UTC, ujjwal0507 requested changes
Please see the comments and do the required changes.

2021-07-16 10:30 UTC, ibmpariwesh commented on backend/sector-service/src/main/java/com/example/sectorservice/entities/Sector.java
> +        return "Sector{" +
use Stringbuilder

2021-07-16 10:31 UTC, ibmpariwesh commented on backend/sector-service/src/main/java/com/example/sectorservice/services/SectorService.java
> +        if(sector.isPresent())
use ternary operator

2021-07-19 04:22 UTC, ujjwal0507 approved these changes
Okay

2021-07-19 04:22 UTC, merged